# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :setupCertificates do
    runner_temp = ENV['RUNNER_TEMP'] || '/tmp'
    keychain_path = File.join(runner_temp, 'app-signing.keychain-db')
    keychain_password = ENV['KEYCHAIN_PASSWORD']
    
    cert(
      api_key_path: './fastlane.json',
      keychain_path: keychain_path,
      keychain_password: keychain_password
    )
    sigh(
      api_key_path: './fastlane.json',
      provisioning_name: 'Github Actions Profile',
    )
  end

  desc "Push a new beta build to TestFlight"
  lane :uploadToBeta do
    upload_to_testflight(
      api_key_path: './fastlane.json',
      ipa: "../build/ios/ipa/badgemagic.ipa", 
      skip_waiting_for_build_processing: true,
      groups: 'External Testing Group'
    )
  end
end
